version: '2'
services:
    nginx:
      image: nginx:alpine
      container_name: teste-zapito-nginx
      restart: unless-stopped
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 80:80
    php-fpm:
      build: docker/php-fpm
      user: ${UID}:${UID}
      container_name: teste-zapito
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
    database:
      image: mysql:latest
      container_name: teste-zapito-database
      restart: unless-stopped
      volumes:
        - ./docker/database:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - ${DB_PORT}:3306
